name: PromptStereo
train_iters: 16
valid_iters: 32
instance:
  _target_: model.promptstereo.PromptStereoV15
  cfg:
    feat_dim: [64, 128, 192, 256]
    stem_dim: [32, 64, 128, 192, 256]
    gwc_max_disp: 192
    gwc_group: 8
    corr_level: 2
    corr_radius: 4
    scale_list : [0.25, 0.5, 2.0, 4.0]
    n_downsample: 2
    lbp_offsets_str: (-1,-1), (1,1), (1,-1), (-1,1)
    #需与上对应
    lbp_dim: 4
    modulation_hidden_dim:
    modulation_ratio: 1.0
    feat_attn_win_size: 8
    feat_attn_num_heads: 4
    pretrained_model:
      name: DepthAnythingV2
      checkpoint: /data/wht/checkpoints/monster/depth_anything_v2_vitl.pth
      features: 256
      out_channels: [256, 512, 1024, 1024]
      use_bn: False
      instance:
        _target_: model.depth_anything_v2.DepthAnythingV2
        encoder: vitl
        features: ${..features}
        out_channels: ${..out_channels}
        use_bn: False
        use_clstoken: False